---
- name: Host | hostname | update inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_hostname != inventory_hostname

- name: Host | timezone | update timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"
