---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops-cert-manager-cert-manager-app
  namespace: flux-system
  labels:
    customize.fluxcd.io/substitute: disabled
spec:
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ops
  path: ./k8s/blackpearl/system/cert-manager/app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops-cert-manager-cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: ops-cert-manager-cert-manager-app
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ops
  path: ./k8s/blackpearl/system/cert-manager/issuer
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager-app
      namespace: cert-manager
