---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops-weave-gitops-gitops-app
  namespace: flux-system
spec:
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ops
  path: ./k8s/blackpearl/system/weave-gitops/app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gitops-app
      namespace: flux-system
