---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ops
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/drizztdoud/ops
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include k8s directory
    !/k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops
  namespace: flux-system
spec:
  interval: 30m
  path: ./k8s/blackpearl/flux-system
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: ops
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
