---
# standalone
zerg:
  hosts:
    mutalisk: {}
    scourge: {}
    lurker: {}

# k8s
blackpearl:
  hosts:
    blackpearl-master:
      ansible_host: 192.168.64.130
  children:
    blackpearl-workers:
      hosts:
        blackpearl-worker-01:
          ansible_host: 192.168.64.131
        blackpearl-worker-02:
          ansible_host: 192.168.64.132
        blackpearl-worker-03:
          ansible_host: 192.168.64.133
