---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: ingress-nginx
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      remediateLastFailure: true
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    controller:
      extraEnvs:
        - name: TZ
          value: ${TIMEZONE}
      service:
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      extraArgs:
        default-ssl-certificate: ingress-nginx/letsencrypt-prod-tls
      config:
        use-forwarded-headers: "true"
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.21.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
