---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops-metallb-system-metallb-app
  namespace: flux-system
  labels:
    customize.fluxcd.io/substitute: disabled
spec:
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ops
  path: ./k8s/blackpearl/system/metallb-system/app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops-metallb-system-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: ops-metallb-system-metallb-app
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ops
  path: ./k8s/blackpearl/system/metallb-system/config
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: metallb-app
      namespace: metallb-system
