---
- name: Preparation for k8s 'blackpearl'
  hosts: blackpearl

  vars:
    timezone: Asia/Shanghai
    openssh_port: 2022
    apt_packages:
      - ca-certificates
      - curl
      - dnsutils
      - git
      - htop
      - locales-all
      - neofetch
      - net-tools
      - python3-pip
      - tmux
      - vim

  pre_tasks:
    - name: Pausing for 3 seconds...
      ansible.builtin.pause:
        seconds: 3
      tags: always

  roles:
    - os.debian-init

  post_tasks:
    - name: Kernel | Enable kernel modules now
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop: [br_netfilter, overlay]

    - name: Kernel | Enable kernel modules on boot
      ansible.builtin.copy:
        mode: 0644
        content: "{{ item }}"
        dest: "/etc/modules-load.d/{{ item }}.conf"
      loop: [br_netfilter, overlay]

    - name: Sysctl | kubernetes
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/99-kubernetes.conf
        reload: true
      with_dict: "{{ sysctl_config }}"
      vars:
        sysctl_config:
          net.ipv4.ip_forward: 1
          net.ipv4.conf.all.forwarding: 1
          net.ipv4.conf.all.rp_filter: 0
          net.ipv4.conf.default.rp_filter: 0
          net.ipv6.conf.all.forwarding: 1
          net.bridge.bridge-nf-call-iptables: 1
          net.bridge.bridge-nf-call-ip6tables: 1
          fs.inotify.max_user_watches: 524288
          fs.inotify.max_user_instances: 512

- name: Preparation for Worker Nodes
  hosts: blackpearl-workers
  gather_facts: false

  tasks:
    - name: Install package(s)
      ansible.builtin.apt:
        name: "{{ item }}"
      loop:
        # for longhorn
        - open-iscsi
        - nfs-common
