---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ops-longhorn-system-longhorn-app
  namespace: flux-system
  labels:
    customize.fluxcd.io/substitute: disabled
spec:
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: ops-k8s
  path: ./k8s/blackpearl/system/longhorn-system/app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn-app
      namespace: longhorn-system
